export const ProductRows = [
  {
    id: 1,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 2,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 3,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 4,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 5,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 6,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 7,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 8,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 9,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
  {
    id: 10,
    name: "apple airpod",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCBBnvtrUFdeCfqtxw301IR3WxlCaq6uzTSQ&usqp=CAU",
    stock: 123,
    status: "active",
    price: "12000",
  },
];
